#!/usr/bin/env bash

unknown_flag() {
    echo "unknown flag: $1"
    echo
    echo "flag combos:"
    echo " w - Run in the Wine jail"
    echo " s - Run in the Steam jail"
    echo " n - Run without network access"
    echo " d - Run in the specified private directory"
}

JAIL_LOCATION=""
RUN_FLAGS=(--noprofile --blacklist=/media/)
ARG_OFFSET=2

while read -n1 char; do
    case $char in
        w)
            JAIL_LOCATION=~/games/
            mkdir -p $JAIL_LOCATION
            ;;
        s)
            JAIL_LOCATION=~/games/steam/
            mkdir -p $JAIL_LOCATION
            ;;
        n)
            RUN_FLAGS+=(--net=none)
            ;;
        d)
            JAIL_LOCATION=~/jail/$2
            mkdir -p $JAIL_LOCATION
            ((++ARG_OFFSET))
            ;;
        *)
            unknown_flag $char
            exit 1
            ;;
    esac
done < <(echo -n "$1")

if [[ ! -z $JAIL_LOCATION ]]; then
    RUN_FLAGS+=(--private=$JAIL_LOCATION)
else
    RUN_FLAGS+=(--private)
fi

exec firejail ${RUN_FLAGS[@]} "${@:$ARG_OFFSET}"
