series_dir = '/home/jonathan/anime'
reset_dates_on_rewatch = false

[episode]
percent_watched_to_progress = 50.0
player = 'mpv'
player_args = ["--profile=anime1080", "--fs"]
[tui.keys]
play_next_episode = '''

'''
